thoth-station/solver

thoth/solver/python.py

Mark packages that couldn't be found as unresolvable

---

thoth/solver/python.py

Keep track of unparsed packages

---

thoth/solver/python.py

this closes https://github.com/thoth-station/solver/issues/134

if error is not fatal, loglevel has been replaced with warning

---

openshift/job-template.yaml

Introduce THOTH_SOLVER_INDEXES variable in template

---

openshift/job-template.yaml

Use solver naming convention

---

.gitignore
thoth/solver/python/python.py

Fix debug message printed

---

.coafile
openshift/buildConfig-template.yaml
openshift/imageStream-template.yaml
openshift/job-template.yaml

maybe https://github.com/thoth-station/solver/pull/186/files#diff-11739a360acb08301348981f06863798R127 is worth looking at

added f28, f29 solvers, relocked pipfile

---

openshift/job-template.yaml

using the correct name now

---

openshift/job-template.yaml

Related-To: https://github.com/thoth-station/thoth-ops/issues/20

added ImageStream namespace and tag

---

openshift/buildConfig-template.yaml

we need to provide a pull secret

---

thoth/solver/python/python.py

a little bit more verbosity

---

thoth/solver/python/python.py

Fixes: https://github.com/thoth-station/solver/issues/219

Retry if subgraph check API does not respond with correct status code

---

README.rst

modify link

---

thoth/solver/python/python.py

Depends-On: https://github.com/thoth-station/storages/pull/730

Check if the given package in the given version was solved by specific solver

---

thoth/solver/python/python.py

Restarting solver is expensive operation, try to retry in case of remte
disconnects.
Fixes: https://github.com/thoth-station/solver/issues/268

Retry if client gets disconnected

---

openshift/job-template.yaml

Depends-On: https://github.com/thoth-station/common/pull/462

Be consistent with labels on solvers

---

thoth/solver/python/python.py

Perform backoff and fix connection only errors

---

thoth/solver/python/base.py

Fix issue when fetcher kwargs are set to None

---

thoth/solver/python/python.py

Implicitly turn off subgraph checks if transitive will not be resolved

---

openshift/job-template.yaml

Fixes: #297 
Use only ubi based image in job

Use only ubi based image in job

---

thoth/solver/python/python.py

Fix gathering of hashes for packages which have different versions on PyPI

---

thoth/solver/cli.py

Depends-On: https://github.com/thoth-station/analyzer/pull/186

Add duration to Solver

---

Pipfile
Pipfile.lock
thoth/solver/python/python.py

Reverts thoth-station/solver#294

Revert "WIP: Aggregate package metadata for markers and extras"

---

thoth/solver/__init__.py

Bump version

---

thoth/solver/python/python.py

Fixes: https://github.com/thoth-station/solver/issues/320

Be consistent with index_url and package_version

---

openshift/buildConfig-template.yaml

Update the cmd as python

---

openshift/buildConfig-template.yaml

Update the cmd as python in all solver images

Update the cmd as python in all solver images

---

openshift/buildConfig-template.yaml
openshift/job-template.yaml

Name Conversion of ubi to rhel 8.0.
- to fix /etc/os-release
Fixes: https://github.com/thoth-station/solver/pull/340#discussion_r338453234

Name Conversion of ubi to rhel 8.0

---

thoth/solver/python/python.py

Correctly report issues when aggregating metadata for old packages

---

openshift/job-template.yaml

Fixing metadata part, missed previously
Already fixed in the cluster 

Fixing metadata part, missed previously

---

.zuul.yaml
openshift/buildConfig-template.yaml
openshift/imageStream-template.yaml
openshift/job-template.yaml

updated templates with annotations and param thoth-advise-value

updated templates with annotations and param thoth-advise-value

---

README.rst

Add README metadata based on the current implementation

---

openshift/buildConfig-template.yaml
openshift/job-template.yaml
thoth/solver/cli.py
thoth/solver/python/python.py

Provide an option to pass pre-built virtualenvironment

---

openshift/buildConfig-template.yaml

Upgrade setuptools present in the base image on build

---

openshift/buildConfig-template.yaml

build from the latest release of ubi8

---

openshift/buildConfig-template.yaml
openshift/imageStream-template.yaml

introduced rhel81 solver, and fixed rhel80 solver (by building from earlier tag)

introduced rhel81 solver

---

.zuul.yaml
openshift/buildConfig-template.yaml
openshift/imageStream-template.yaml

f30 & f31  based solver images
- python 3.6 and 3.7 compatible 
- fixed python3.6 pip issue 

f30 & f31  based solver images

---

thoth/solver/python/python.py

Related: https://github.com/thoth-station/storages/pull/1349

Propagate information whether the given package and version is provided by index

---

openshift/all-jobs-template.yaml

all solver jobs for production and stage cluster

all solver jobs for production and stage cluster

---

thoth/solver/python/python.py

Related: https://github.com/thoth-station/solver/pull/424

Format using black, add ignore comments for dict specific types

---

openshift/solve_and_sync-template.yaml
workflows/templates/solver-template.yaml

Standardize solver name variable

---

openshift/all-jobs-template.yaml
openshift/buildConfig-template.yaml
openshift/imageStream-template.yaml
openshift/job-template.yaml
openshift/solve_and_sync-template.yaml

Related: https://github.com/thoth-station/storages/pull/1515

Rename solver-rhel-8.0 to solver-rhel-8

---

openshift/job-template.yaml

Fixes: https://github.com/thoth-station/metrics-exporter/issues/288
Depends-On: https://github.com/thoth-station/common/pull/628

Update template name

---

openshift/job-template.yaml
openshift/solve_and_sync-template.yaml

Adjust name and volume in templates

---

openshift/all-jobs-template.yaml

Use solver-workload-operator name for stage solver jobs
- fixed parameters according to the requirements.

Use solver-workload-operator name for stage solver jobs

---

workflows/templates/solver-template.yaml

Missing paranthesis prevent sync on Ceph

---

workflows/templates/solver-template.yaml

More resources for bigger stacks

---

openshift/solve_and_sync-template.yaml

introduce logic for Podgc and workflows life

---

openshift/solve_and_sync-template.yaml

Keep workflows for SLI

---

thoth/solver/python/instrument.py

Fixes: https://github.com/thoth-station/python/issues/291

Make thoth-solver work with Python 3.8+

---

thoth/solver/python/instrument.py

Related: https://github.com/python/mypy/issues/1153

Fix mypy errors for duplicate imports

---

dockerfile/Dockerfile.solver-fedora-28-py36
dockerfile/Dockerfile.solver-fedora-29-py36
dockerfile/Dockerfile.solver-fedora-29-py37
dockerfile/Dockerfile.solver-fedora-30-py36
dockerfile/Dockerfile.solver-fedora-30-py37
dockerfile/Dockerfile.solver-fedora-31-py36
dockerfile/Dockerfile.solver-fedora-31-py37
dockerfile/Dockerfile.solver-fedora-31-py38
dockerfile/Dockerfile.solver-fedora-32-py37
dockerfile/Dockerfile.solver-fedora-32-py38
dockerfile/Dockerfile.solver-rhel-8-py36
dockerfile/Dockerfile.solver-rhel-8.1-py36

thoth solver dockerfiles
All the docker files corresponding to different solver images are present here.

thoth solver dockerfiles

---

.aicoe-ci.yaml
pipeline.yaml

support solver image build with ci pipeline

support solver image build with ci pipeline

---

Pipfile
Pipfile.lock
requirements.txt

Do not use environment marker for importlib-metadata

---

dockerfile/Dockerfile.solver-rhel-8-py38
pipeline.yaml

solver based on ubi8 and python38

solver based on ubi8 and python38

---

.thoth.yaml

See discussion in https://github.com/thoth-station/solver/pull/662#issuecomment-771077105

Remove old Fedora S2I images

---

README.rst

Updates related to builds will be covered in https://github.com/thoth-station/thoth-application/issues/825

Update README and remove old build section

---

.aicoe-ci.yaml

Run pytest with Python 3.8

---

Pipfile.lock
tests/python/instrument_test.py
thoth/solver/python/instrument.py

Fix CI failures

---

thoth/solver/python/python.py

Skip thoth-solver in the environment packages report

---

README.rst

Improvements to docs

---

thoth/solver/cli.py
thoth/solver/python/python.py

Fixes: https://github.com/thoth-station/thoth-application/issues/1153

Provide an ability to limit output

---

tests/data/metadata/click.json
tests/data/metadata/delegator-py.json
tests/python/instrument_test.py
tests/python/python_test.py
thoth/solver/python/instrument.py
thoth/solver/python/python.py

This should fix related failures in tests.

Metadata now gather also description

---

thoth/solver/python/python.py

Related: https://github.com/thoth-station/thoth-application/issues/1280

Compute packages available in analyzed Python package release

---

thoth/solver/python/python.py

Fixes: https://github.com/thoth-station/solver/issues/703

Raise on exit code propagating a signal from operating system

---

thoth/solver/python/python.py

Remove unnecessary whitespace

---

.aicoe-ci.yaml
.thoth.yaml
README.rst

Related: https://github.com/thoth-station/s2i-thoth/pull/184/
Related: https://github.com/thoth-station/solver/issues/663

Add Fedora 34 based on Python 3.9 solver

---

README.rst

Related: https://github.com/thoth-station/s2i-thoth/pull/191

Remove Fedora 31 + Python 3.7 it went EOL

---

overlays/solver-fedora-30-py36/Pipfile.lock
overlays/solver-fedora-30-py37/Pipfile.lock
overlays/solver-fedora-31-py36/Pipfile.lock
overlays/solver-fedora-31-py37/Pipfile.lock
overlays/solver-fedora-31-py38/Pipfile.lock
overlays/solver-fedora-32-py37/Pipfile.lock
overlays/solver-fedora-32-py38/Pipfile.lock
overlays/solver-fedora-34-py39/Pipfile.lock
overlays/solver-rhel-8-py36/Pipfile.lock
overlays/solver-rhel-8-py38/Pipfile.lock

update the dependencies of the overlays
```
Traceback (most recent call last):
File "thoth/solver/cli.py", line 30, in <module>
from thoth.solver import __title__ as analyzer_name
File "/opt/app-root/lib64/python3.8/site-packages/thoth/solver/__init__.py", line 20, in <module>
from .python import get_ecosystem_solver
File "/opt/app-root/lib64/python3.8/site-packages/thoth/solver/python/__init__.py", line 24, in <module>
from .python import resolve
File "/opt/app-root/lib64/python3.8/site-packages/thoth/solver/python/python.py", line 33, in <module>
from thoth.python.exceptions import NotFoundError
ImportError: cannot import name 'NotFoundError' from 'thoth.python.exceptions' (/opt/app-root/lib64/python3.8/site-packages/thoth/python/exc …
```

update the dependencies of the overlays

---

setup.py

Increase pytest timeout

---

thoth/solver/python/python.py

Related: https://github.com/thoth-station/python/pull/452

Raise an error if no artifact hashes are found

---

README.rst

Adjust doc to current CLI implementation

---

docs/source/index.rst

Fixes: https://github.com/thoth-station/thoth-application/issues/2536
Documentation has been added for creating new solvers.

adding documentation on creating new solver overlays

---

overlays/solver-fedora-34-py39/Pipfile
overlays/solver-fedora-34-py39/Pipfile.lock
overlays/solver-fedora-35-py310/Pipfile
overlays/solver-fedora-35-py310/Pipfile.lock
overlays/solver-rhel-8-py36/Pipfile
overlays/solver-rhel-8-py36/Pipfile.lock
overlays/solver-rhel-8-py38/Pipfile
overlays/solver-rhel-8-py38/Pipfile.lock

Upgrade the dependencies for the solver overlays

Upgrade the dependencies for the solver overlays

---

Pipfile.lock
overlays/solver-fedora-35-py310/Pipfile.lock
thoth/solver/python/python.py

Catch the 403 from the index which are forbidden
Related-to: https://github.com/thoth-station/solver/issues/5182

Catch the 403 from the index which are forbidden

---

overlays/solver-fedora-34-py39/Pipfile.lock
overlays/solver-fedora-35-py310/Pipfile.lock

Update overlay fedora-35-py3.10 dependencies

:pushpin: Update overlay fedora-35-py3.10 and fedora34-py3.9 dependencies
