thoth-station/solver

Pipfile.lock
Dependency virtualenv was used in version 15.2.0, but the current latest version is 16.0.0.
=> Automatic update of dependency virtualenv from 15.2.0 to 16.0.0

Pipfile.lock
Dependency thoth-common was used in version 0.0.3, but the current latest version is 0.0.6.
=> Automatic update of dependency thoth-common from 0.0.3 to 0.0.6

openshift/job-template.yaml
As we own logic for solver, solver should keep restarting in case of errors so
that we see what is wrong.
Fixes: #188
=> Restart solver run if anything goes wrong

.zuul.yaml, openshift/buildConfig-template.yaml
Add generic trigger webhook to buildconfig
The `generic-webhook-secret` secret is a prerequisite for using this new build config.
Add trigger build job to zuul post pipeline job list
=> Add build trigger with generic webhook

thoth/solver/python/python.py
To optimize solver runs inside the cluster, let's also perform sub-graph checks
on resolved direct dependencies.
=> Do sub-graph checks also on direct dependencies

tests/python/test_instrument.py, thoth/solver/python/instrument.py, thoth/solver/python/python.py
This way, we will import packages which are present in the virtual env
first, then injecteted packages into virtual environment.
This is a fix for an issue where we analyze click package, which is also a 
dependency of thoth-solver. As the precedence is given first to path
injected by PYTHONPATH environment variable, we always return metadata for
click which is installed for thoth-solver (not the analyzed one).
Depends-On: #327 #326
=> Reverse order of imports during venv instrumentation

openshift/imageStream-template.yaml
Updated Imagestream from ubi to rhel
Fixed this already on the openshift namespace, just for consistency.
=> Updated Imagestream from ubi to rhel

openshift/buildConfig-template.yaml
Install py3.6 as base python in f29
Fixes: As older dockerfile fails 
```
RUN cd ${THOTH_SOLVER_TMP_DIR} &&pip3 install . &&cd / &&rm -rf ${THOTH_SOLVER_TMP_DIR} &&unset THOTH_SOLVER_TMP_DIR &&dnf clean all &&chmod 777 /home/solver
--
  | ---> Running in 27cf22909b63
  | Traceback (most recent call last):
  | File "/usr/bin/pip3", line 8, in <module>
  | from pip._internal import main
  | ModuleNotFoundError: No module named 'pip'
  | During handling of the above exception, another exception occurred:
  | Traceback (most recent call last):
  | File "/usr/bin/pip3", line 12, in <module>
  | from pip import main
  | ModuleNotFoundError: No module named 'pip'
```
=> Install py3.6 as base python in f29

openshift/job-template.yaml
* as solver resolves one package-version at a time, we should be fine with
lowering memory requests needed for a solver job
=> Lower requests for running solver jobs

openshift/job-template.yaml
Let's have one centralized point for conifguring this - cleanup job itself.
Related: https://github.com/thoth-station/cleanup-job/pull/215
=> Remove ttl configuration for cleanup

openshift/buildConfig-template.yaml
We need to create pre-built solver environment before applying permission
changes so that the venv has correct permissions assigned (and an arbitrary
openshift user can install packages into it).
=> Fix permission issues in solver runs

thoth/solver/python/python.py
This addresses issues for unsolved packages - for example ansible==2.0.0 will
install ansible==2.0.0.0 leaving ansible=2.0.0 marked as unsolved in the
knowledge graph.
=> Use arbitrary equality for solvers

openshift/all-jobs-template.yaml, openshift/job-template.yaml
Some of the solvers (especially those that required building artifacts
during pip install) failed in stage environment because of insufficient
memory requirements.
Depends-On: #422
=> Increase memory requirements for solvers

thoth/solver/python/instrument.py
If the JSON flag is set to True and no output is produced, solver raises an
exception when trying to serialize JSON output. This patch moves the
serialization after the check so that the undesired exception does not occur.
=> Fix when no output was produced and JSON flag was set to true

workflows/templates/solver-template.yaml
consistency in workflow while using secrets
The workflow-controller on deployment creates a secret named: argo-artifact-repository-secrets
https://github.com/thoth-station/ansible-role-argo-workflows/blob/7233110287bb1dc198a446554398929d84e52e09/templates/secrets/secrets.yaml#L4
Feel like secret argo-artifact-repository is redundant
=> consistency in workflow while using secrets

tests/python/python_solver_test.py, thoth/solver/python/python_solver.py
When parsing pre-releases with no specifier, resolver removes packages that have pre-releases. This is undesired behavior as we want to handle pre-releases in pipeline units.
=> Explicitly turn on pre-releases in Python dependency parser

app.py, app.sh
Execute solvers with app script to call solver python cli
As we moved to s2i based solver, the cli command is not being passed with **command-options**, which earlier use to happen with entrypoint and cmd feature of the dockerfile based image. 
with this we can execute the **app.sh** script to have the same behaviour.
```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1614841351.7242138, "asctime": "2021-03-04 07:02:31,724", "msecs": 724.2138385772705, "relative_created": 760.1261138916016, "process": 8, "message": "Logging to a Sentry instance is turned off"}
Usage: app.py [OPTIONS] COMMAND [ARGS]...
Thoth solver command line interface.
Options:
-v, …
```
=> Execute solvers with app script to call solver python cli

thoth/solver/cli.py
When running thoth-solver locally, the logger is not properly setup to debug level as the logger is called "thoth.solver.cli" instead of "thoth.solver".
=> Use thoth.solver logger in the CLI setup

thoth/solver/cli.py, thoth/solver/python/python.py
Related: https://github.com/thoth-station/solver/issues/5111
Related: https://github.com/thoth-station/graph-refresh-job/issues/669
Related: https://github.com/thoth-station/thoth-application/issues/2272
Pass all registered indexes when scheduling solver workflow.
=> Look for dependency versions on separate dependency indexes

.aicoe-ci.yaml, .thoth.yaml, overlays/solver-fedora-35-py310/Pipfile, overlays/solver-fedora-35-py310/Pipfile.lock
Addresses: https://github.com/thoth-station/s2i-thoth/issues/231
Related to: https://github.com/thoth-station/s2i-thoth/pull/235
Create a new solver image from recently created base image https://quay.io/repository/thoth-station/s2i-thoth-f35-py310/.
=> creating deployment overlay for solver-f35-py310

.aicoe-ci.yaml, .pre-commit-config.yaml, .prow.yaml, .thoth.yaml, OWNERS, overlays/solver-rhel-9-py39/Pipfile, overlays/solver-rhel-9-py39/Pipfile.lock
Introduce new solver for ubi9 python 39 stack
Fixes: https://github.com/thoth-station/s2i-thoth/issues/234
=> Introduce solver ubi9

thoth/solver/cli.py
This should help diagnoses thoth-station/thoth-application#2690
We should get some stacktrace, which will help us locate where our python code allocates a lot. (Especially if we have a space complexity bug/problem)
We try to convert OOM-kill at the cgroup level into python MemoryError.
The method employed has a number of caveats:
- setrlimit only acts on one process, when cgroup is a group of process
; other process in the container could also consume memory
- the OOM-killer might still kick in before Python raising MemoryError,
depending on the particular of the Python allocator
=> Limit memory usage based on cgroup info
